server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

 # Health endpoint
  location /healthz {
      return 200 'okayyy';
      add_header Content-Type text/plain;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}



